# Generated by Django 5.2.14 on 2026-05-20 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('market', models.CharField(choices=[('KOSPI', '코스피'), ('KOSDAQ', '코스닥'), ('NASDAQ', '나스닥'), ('NYSE', '뉴욕증권거래소')], max_length=16)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('listed_at', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('KRW', '원'), ('USD', '달러')], max_length=8)),
                ('kis_short_code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_sp500', models.BooleanField(default=False)),
                ('is_nasdaq100', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['market', 'is_active'], name='stocks_stoc_market_3a905a_idx'), models.Index(fields=['is_sp500'], name='stocks_stoc_is_sp50_db0de1_idx'), models.Index(fields=['is_nasdaq100'], name='stocks_stoc_is_nasd_8e3508_idx')],
                'constraints': [models.UniqueConstraint(fields=('code', 'market'), name='stock_code_market_unique')],
            },
        ),
        migrations.CreateModel(
            name='StockNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500, unique=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('published_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['-published_at'], name='stocks_stoc_publish_cec2e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_period', models.CharField(max_length=16)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('operating_profit', models.BigIntegerField(blank=True, null=True)),
                ('net_profit', models.BigIntegerField(blank=True, null=True)),
                ('operating_margin', models.FloatField(blank=True, null=True)),
                ('net_margin', models.FloatField(blank=True, null=True)),
                ('revenue_yoy', models.FloatField(blank=True, null=True)),
                ('operating_profit_yoy', models.FloatField(blank=True, null=True)),
                ('net_profit_yoy', models.FloatField(blank=True, null=True)),
                ('debt_ratio', models.FloatField(blank=True, null=True)),
                ('equity_ratio', models.FloatField(blank=True, null=True)),
                ('current_ratio', models.FloatField(blank=True, null=True)),
                ('payout_ratio', models.FloatField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('DART', 'DART'), ('yfinance', 'yfinance')], max_length=16)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='financials', to='stocks.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'fiscal_period'), name='financialsummary_stock_period_unique')],
            },
        ),
        migrations.CreateModel(
            name='StockIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per', models.FloatField(blank=True, null=True)),
                ('pbr', models.FloatField(blank=True, null=True)),
                ('eps', models.IntegerField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('roa', models.FloatField(blank=True, null=True)),
                ('dividend_yield', models.FloatField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('high_52w', models.IntegerField(blank=True, null=True)),
                ('low_52w', models.IntegerField(blank=True, null=True)),
                ('calculated_date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='indicators', to='stocks.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'calculated_date'), name='stockindicator_stock_date_unique')],
            },
        ),
        migrations.CreateModel(
            name='NewsRelatedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_news', to='stocks.stock')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_stocks', to='stocks.stocknews')),
            ],
            options={
                'indexes': [models.Index(fields=['stock'], name='stocks_news_stock_i_cd443e_idx')],
                'constraints': [models.UniqueConstraint(fields=('news', 'stock'), name='newsrelatedstock_unique')],
            },
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_date', models.DateField()),
                ('open', models.DecimalField(decimal_places=4, max_digits=18)),
                ('high', models.DecimalField(decimal_places=4, max_digits=18)),
                ('low', models.DecimalField(decimal_places=4, max_digits=18)),
                ('close', models.DecimalField(decimal_places=4, max_digits=18)),
                ('volume', models.BigIntegerField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prices', to='stocks.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'price_date'), name='stockprice_stock_date_unique')],
            },
        ),
    ]
