# Generated by Django 5.2.14 on 2026-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='ceo_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='employee_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='homepage_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
