# Generated by Django 5.2.14 on 2026-06-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_ceo_name_stock_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=120)),
                ('importance', models.CharField(choices=[('HIGH', '상'), ('MEDIUM', '중'), ('LOW', '하')], default='MEDIUM', max_length=8)),
                ('country', models.CharField(choices=[('US', '미국'), ('KR', '한국')], max_length=4)),
            ],
            options={
                'ordering': ['event_date', 'id'],
                'indexes': [models.Index(fields=['event_date'], name='stocks_econ_event_d_7596fc_idx'), models.Index(fields=['country', 'event_date'], name='stocks_econ_country_ffd641_idx')],
            },
        ),
    ]
