# Generated by Django 5.2.14 on 2026-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_economicevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsrelatedstock',
            name='relevance_score',
            field=models.DecimalField(decimal_places=3, default=1, help_text='매칭 신뢰도(제목매칭 1.0 등)·정렬용', max_digits=4),
        ),
    ]
