# Generated by Django 5.2.14 on 2026-05-20 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도'), ('WATCH', '관심')], max_length=8)),
                ('reason_category', models.CharField(blank=True, max_length=50)),
                ('reason_text', models.TextField()),
                ('confidence', models.PositiveSmallIntegerField()),
                ('target_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('diary_date', models.DateField()),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='portfolio.order')),
                ('related_news', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diaries', to='stocks.stocknews')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='diaries', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiaryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('judgment', models.CharField(blank=True, max_length=50)),
                ('lesson', models.TextField()),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('diary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='diary.stockdiary')),
            ],
        ),
        migrations.AddIndex(
            model_name='stockdiary',
            index=models.Index(fields=['user', '-diary_date'], name='diary_stock_user_id_a1144e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdiary',
            index=models.Index(fields=['order'], name='diary_stock_order_i_c819c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockdiary',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 1), ('confidence__lte', 5)), name='diary_confidence_1_5'),
        ),
        migrations.AddConstraint(
            model_name='stockdiary',
            constraint=models.CheckConstraint(condition=models.Q(('action_type__in', ['BUY', 'SELL', 'WATCH'])), name='diary_action_type_enum'),
        ),
    ]
