# Generated by Django 5.2.14 on 2026-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockdiary',
            name='reason_text',
        ),
        migrations.RemoveField(
            model_name='stockdiary',
            name='related_news',
        ),
        migrations.AlterField(
            model_name='stockdiary',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('GROWTH', '장기 성장성'), ('EARNINGS', '실적 개선'), ('UNDERVALUED', '저평가'), ('THEME', '테마/모멘텀'), ('NEWS', '뉴스 호재'), ('TECHNICAL', '기술적 반등'), ('DIVIDEND', '배당 매력'), ('DIVERSIFY', '분산 목적')], max_length=20),
        ),
    ]
