# Generated by Django 5.2.14 on 2026-06-22 08:41

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_remove_stockdiary_reason_text_and_more'),
        ('portfolio', '0005_holding_base_match_score_holding_base_pbr_and_more'),
        ('stocks', '0004_newsrelatedstock_relevance_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockdiary',
            name='diary_stock_user_id_a1144e_idx',
        ),
        migrations.RemoveField(
            model_name='stockdiary',
            name='diary_date',
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='memo',
            field=models.TextField(blank=True, help_text='선택 입력: 자유 서술 메모'),
        ),
        migrations.AddField(
            model_name='stockdiary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='stockdiary',
            index=models.Index(fields=['user', '-created_at'], name='diary_stock_user_id_90911e_idx'),
        ),
    ]
