# Generated by Django 5.2.14 on 2026-06-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_stockdiary_diary_stock_user_id_a1144e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdiary',
            name='reason_category',
            field=models.CharField(blank=True, choices=[('GROWTH', '장기 성장성'), ('EARNINGS', '실적 개선'), ('UNDERVALUED', '저평가'), ('THEME', '테마/모멘텀'), ('NEWS', '뉴스 호재'), ('TECHNICAL', '기술적 반등'), ('DIVIDEND', '배당 매력'), ('DIVERSIFY', '분산 목적'), ('TARGET_HIT', '목표 달성'), ('STOP_LOSS', '손절'), ('PROFIT_TAKING', '차익 실현'), ('DETERIORATED', '펀더멘털 악화'), ('BETTER_OPP', '더 좋은 기회'), ('REBALANCE', '리밸런싱')], max_length=20),
        ),
    ]
