# Generated by Django 5.2.14 on 2026-06-11 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_commentlike'),
        ('stocks', '0004_newsrelatedstock_relevance_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='communitypost',
            name='community_c_post_ty_fc43a0_idx',
        ),
        migrations.RemoveField(
            model_name='communitypost',
            name='post_type',
        ),
        migrations.AddField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('QUESTION', '질문'), ('REVIEW', '후기'), ('ANALYSIS', '분석'), ('SHARE', '공유')], default='QUESTION', max_length=10),
        ),
        migrations.AddField(
            model_name='communitypost',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='communitypost',
            index=models.Index(fields=['category', '-created_at'], name='community_c_categor_c6128e_idx'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('follower', 'following'), name='follow_follower_following_unique'),
        ),
    ]
