# Generated by Django 5.2.14 on 2026-05-19 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('per', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('bps', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
