# Generated by Django 5.2.14 on 2026-05-19 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
