# Generated by Django 5.2.14 on 2026-05-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_stock_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('per', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('bps', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
