# Generated by Django 5.2.14 on 2026-05-20 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_invalidstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrototypePool',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prototype_pool', serialize=False, to='stocks.stock')),
                ('rank', models.IntegerField(help_text='시가총액 순위 (1~100)')),
                ('code', models.CharField(max_length=10, null=True, unique=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('per', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('eps', models.FloatField(null=True)),
                ('bps', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
