# Generated by Django 5.2.14 on 2026-05-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_prototypepool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prototypepool',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='prototypepool',
            name='bps',
        ),
        migrations.RemoveField(
            model_name='prototypepool',
            name='code',
        ),
        migrations.RemoveField(
            model_name='prototypepool',
            name='eps',
        ),
        migrations.RemoveField(
            model_name='prototypepool',
            name='market_cap',
        ),
        migrations.RemoveField(
            model_name='prototypepool',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prototypepool',
            name='pbr',
        ),
        migrations.RemoveField(
            model_name='prototypepool',
            name='per',
        ),
    ]
