# Generated by Django 5.2.14 on 2026-05-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_prototypepool_beta_remove_prototypepool_bps_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prototypepool',
            options={'ordering': ['rank'], 'verbose_name': '프로토타입 풀 종목', 'verbose_name_plural': '프로토타입 풀 종목들'},
        ),
        migrations.AddField(
            model_name='prototypepool',
            name='beta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prototypepool',
            name='bps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prototypepool',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prototypepool',
            name='eps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prototypepool',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prototypepool',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prototypepool',
            name='pbr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prototypepool',
            name='per',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
