# Generated by Django 5.2.14 on 2026-05-20 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_prototypepool_options_prototypepool_beta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prototypepool',
            name='rank',
            field=models.IntegerField(help_text='시가총액 순위 (1~200)'),
        ),
    ]
