# Generated by Django 5.2.14 on 2026-05-20 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_reorder_prototypepool_columns'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prototypepool',
            options={'ordering': ['-market_cap'], 'verbose_name': '프로토타입 풀 종목', 'verbose_name_plural': '프로토타입 풀 종목들'},
        ),
    ]
