# Generated by Django 5.2.14 on 2026-05-20 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_prototypepool_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='beta',
            field=models.FloatField(blank=True, null=True, verbose_name='베타(변동성)'),
        ),
    ]
