# Generated by Django 5.2.14 on 2026-05-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprofile',
            name='preferred_period',
            field=models.PositiveSmallIntegerField(blank=True, help_text='선호 보유 기간(개월). 예: 1, 3, 6, 12, 24', null=True),
        ),
    ]
