# Generated by Codex on 2026-05-28

from django.db import migrations, models


def forwards(apps, schema_editor):
    investment_profile = apps.get_model('accounts', 'InvestmentProfile')
    investment_profile.objects.filter(risk_type='MODERATE').update(risk_type='BALANCED')


def backwards(apps, schema_editor):
    investment_profile = apps.get_model('accounts', 'InvestmentProfile')
    investment_profile.objects.filter(risk_type='BALANCED').update(risk_type='MODERATE')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_investmentprofile_preferred_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentprofile',
            name='risk_type',
            field=models.CharField(
                choices=[
                    ('CONSERVATIVE', '안정형'),
                    ('BALANCED', '중립형'),
                    ('AGGRESSIVE', '공격형'),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='risk_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='survey_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(forwards, backwards),
    ]
