# Generated by Django 5.2.14 on 2026-06-11 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_investmentprofile_preferred_period'),
        ('stocks', '0003_economicevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentprofile',
            name='behavior',
            field=models.PositiveSmallIntegerField(blank=True, help_text='투자 스타일 1~5', null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, help_text='투자 경험 1~5', null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='investment_term',
            field=models.PositiveSmallIntegerField(blank=True, help_text='투자 기간 1~5', null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='loss_aversion',
            field=models.PositiveSmallIntegerField(blank=True, help_text='손실 회피 1~5', null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='onboarding_answers',
            field=models.JSONField(blank=True, help_text='온보딩 8문항 원답', null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='profiled_at',
            field=models.DateTimeField(blank=True, help_text='프로파일링 완료 시각', null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='risk_tolerance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='리스크 감수 1~5', null=True),
        ),
        migrations.AddField(
            model_name='investmentprofile',
            name='signature_stock',
            field=models.ForeignKey(blank=True, help_text='가입 시점 궁합 1등 종목 박제 (OO형 투자자)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_profiles', to='stocks.stock'),
        ),
        migrations.AddConstraint(
            model_name='investmentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('risk_tolerance__isnull', True), models.Q(('risk_tolerance__gte', 1), ('risk_tolerance__lte', 5)), _connector='OR'), name='profile_risk_tolerance_1_5'),
        ),
        migrations.AddConstraint(
            model_name='investmentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('investment_term__isnull', True), models.Q(('investment_term__gte', 1), ('investment_term__lte', 5)), _connector='OR'), name='profile_investment_term_1_5'),
        ),
        migrations.AddConstraint(
            model_name='investmentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('experience__isnull', True), models.Q(('experience__gte', 1), ('experience__lte', 5)), _connector='OR'), name='profile_experience_1_5'),
        ),
        migrations.AddConstraint(
            model_name='investmentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('loss_aversion__isnull', True), models.Q(('loss_aversion__gte', 1), ('loss_aversion__lte', 5)), _connector='OR'), name='profile_loss_aversion_1_5'),
        ),
        migrations.AddConstraint(
            model_name='investmentprofile',
            constraint=models.CheckConstraint(condition=models.Q(('behavior__isnull', True), models.Q(('behavior__gte', 1), ('behavior__lte', 5)), _connector='OR'), name='profile_behavior_1_5'),
        ),
    ]
