# Generated by Django 5.2.14 on 2026-06-22 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_goal_usergoal_userpreferredsector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentprofile',
            name='risk_type',
        ),
        migrations.AlterField(
            model_name='investmentprofile',
            name='investment_style',
            field=models.CharField(blank=True, help_text='성향 4유형 라벨(가치 파트너형/성장 동반형/단기 승부형/신중 탐색형). 5벡터에서 산출해 저장', max_length=50),
        ),
    ]
