# Generated by Django 5.2.14 on 2026-06-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_investmentprofile_risk_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, help_text='electronics/luxury/travel/car/realestate/life', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, help_text='달성 시 한 줄 멘트', max_length=200),
        ),
        migrations.AddField(
            model_name='goal',
            name='tier',
            field=models.PositiveSmallIntegerField(blank=True, help_text='구간 1~5 (그룹핑용)', null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_amount',
            field=models.BigIntegerField(help_text='누적 수익(총자산-초기지급금) 목표 금액'),
        ),
    ]
