# Generated by Django 5.2.14 on 2026-05-20 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=100000000, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('first_acquired_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='holdings', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', '매수'), ('SELL', '매도')], max_length=8)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('FILLED', '체결'), ('FAILED', '실패')], default='PENDING', max_length=16)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='portfolio.account')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to='stocks.stock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='account_balance_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('user', 'stock'), name='holding_user_stock_unique'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='holding_quantity_nonneg'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='portfolio_o_user_id_50ff59_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['account', 'status'], name='portfolio_o_account_3dde36_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['stock', '-executed_at'], name='portfolio_o_stock_i_126b91_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='order_price_pos'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gt', 0)), name='order_total_pos'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('side__in', ['BUY', 'SELL'])), name='order_side_enum'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'FILLED', 'FAILED'])), name='order_status_enum'),
        ),
    ]
