# Generated by Django 5.2.14 on 2026-06-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_order_fee_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initial_balance',
            field=models.DecimalField(decimal_places=0, default=100000000, max_digits=15),
        ),
    ]
