# Generated by Django 5.2.14 on 2026-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_account_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='realized_pnl',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='매도 실현손익 = (체결가-평균매입가)×수량, 매수는 NULL', max_digits=20, null=True),
        ),
    ]
