# Generated by Django 5.2.14 on 2026-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_order_realized_pnl'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='base_match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='최초 매수 시점 궁합 점수', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='base_pbr',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='최초 매수 시점 PBR (재검증 ±30% 기준)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='last_review_status',
            field=models.CharField(blank=True, choices=[('GREEN', '양호'), ('YELLOW', '주의'), ('RED', '위험')], max_length=8),
        ),
        migrations.AddField(
            model_name='holding',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
