# Generated by Django 5.2.14 on 2026-06-11 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0004_newsrelatedstock_relevance_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoldingMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_days', models.PositiveSmallIntegerField(help_text='30/90/180/365')),
                ('snapshot', models.JSONField(default=dict, help_text='그 시점 지표')),
                ('reached_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'stock', 'milestone_days'), name='milestone_user_stock_days_unique')],
            },
        ),
        migrations.CreateModel(
            name='LongTermScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('growth_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='종목 소계 (재무+성장)', max_digits=5, null=True)),
                ('calculated_date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_scores', to='stocks.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'calculated_date'), name='ltscore_stock_date_unique')],
            },
        ),
        migrations.CreateModel(
            name='LongTermScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recorded_date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_score_history', to='stocks.stock')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', '-recorded_date'], name='recommend_l_stock_i_181da8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecommendationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('onboarding', '온보딩 궁합'), ('long_term', '장투')], default='onboarding', max_length=20)),
                ('match_score', models.DecimalField(decimal_places=2, help_text='0~100', max_digits=5)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reason', models.JSONField(default=dict, help_text='요소별 기여 + 한줄요약')),
                ('expires_at', models.DateTimeField(help_text='TTL: 하루 뒤 만료')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'rec_type', 'rank'], name='recommend_r_user_id_656f66_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'stock', 'rec_type'), name='reccache_user_stock_type_unique')],
            },
        ),
        migrations.CreateModel(
            name='StockDna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volatility', models.DecimalField(blank=True, decimal_places=4, help_text='pct(beta)', max_digits=6, null=True)),
                ('value_score', models.DecimalField(blank=True, decimal_places=4, help_text='pct(1/PBR)', max_digits=5, null=True)),
                ('growth_score', models.DecimalField(blank=True, decimal_places=4, help_text='pct(net_profit_yoy)', max_digits=5, null=True)),
                ('stability', models.DecimalField(blank=True, decimal_places=4, help_text='pct(1/beta)', max_digits=5, null=True)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('calculated_date', models.DateField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna', to='stocks.stock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stock', 'calculated_date'), name='stockdna_stock_date_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserLikedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('base_pbr', models.DecimalField(blank=True, decimal_places=4, help_text='Like 시점 PBR (재검증 ±30% 기준)', max_digits=10, null=True)),
                ('base_match_score', models.DecimalField(blank=True, decimal_places=2, help_text='Like 시점 궁합', max_digits=5, null=True)),
                ('last_review_status', models.CharField(blank=True, choices=[('GREEN', '양호'), ('YELLOW', '주의'), ('RED', '위험')], max_length=8)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='stocks.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_stocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'stock'), name='userlikedstock_user_stock_unique')],
            },
        ),
    ]
