# Generated by Django 5.2.14 on 2026-06-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikedstock',
            name='base_match_score',
        ),
        migrations.RemoveField(
            model_name='userlikedstock',
            name='base_pbr',
        ),
        migrations.RemoveField(
            model_name='userlikedstock',
            name='last_review_status',
        ),
        migrations.RemoveField(
            model_name='userlikedstock',
            name='last_reviewed_at',
        ),
        migrations.DeleteModel(
            name='LongTermScoreHistory',
        ),
    ]
