# Generated by Django 5.2.14 on 2026-06-18 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0004_newsrelatedstock_relevance_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('economy', '경제'), ('politics', '정치'), ('world', '세계')], max_length=16)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_categories', to='stocks.stocknews')),
            ],
            options={
                'indexes': [models.Index(fields=['category'], name='newses_feed_categor_d2ee5b_idx')],
                'constraints': [models.UniqueConstraint(fields=('news', 'category'), name='feednews_news_category_unique')],
            },
        ),
    ]
