# Generated by Django 5.2.14 on 2026-06-18 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newses', '0001_initial'),
        ('stocks', '0004_newsrelatedstock_relevance_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=50)),
                ('score', models.DecimalField(decimal_places=3, default=0, max_digits=4)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='stocks.stocknews')),
            ],
            options={
                'indexes': [models.Index(fields=['sector'], name='newses_news_sector_c6681b_idx')],
                'constraints': [models.UniqueConstraint(fields=('news', 'sector'), name='newssector_news_sector_unique')],
            },
        ),
    ]
